#!/bin/bash

TARGET="/tmp/standaloneGame"
DEBUG="$TARGET.debug"

if [ $# -gt "0" ] ; then
  args=("$@")
  counter=0
  if [ -f "$TARGET" ] ; then rm "$TARGET" ; fi
  if [ -f "$DEBUG" ] ; then rm "$DEBUG" ; fi
  while [ "$counter" -lt $# ] ; do
    echo "${args[$counter]}" >> "$TARGET"
    echo "${args[$counter]}" >> "$DEBUG"
    counter=$((counter+1))
  done
  killall xbmc
fi

