#!/bin/bash

MP3PATH="/home/Media/MP3"
UPLOADPATH="UPLOAD"

if [ ! -d $MP3PATH ] ; then exit ; fi
cd $MP3PATH
if [ ! "$(ls -A $UPLOADPATH)" ] ; then exit ; fi
echo ""
echo "$(date) In: $PWD"

if [ "$(mount|grep -e verkkolevy1)" ] ; then
	rsync -acv --no-g --chmod=ug=rwX,o=rX $UPLOADPATH/* /media/verkkolevy1/Musiikki/Metal/

	find $UPLOADPATH/* -maxdepth 0 -type d|while read i ; do
		MVPATH=$(echo $i|sed 's/UPLOAD\///')
		#if [[ "$MVPATH" == *"/"* ]] ; then
			BAND=$(echo "$MVPATH"|cut -d'/' -f1)
			if [ ! -d "$PWD"/"$BAND" ] ; then mkdir "$PWD"/"$BAND" && echo "Created folder \"$BAND\""; fi
			find $i/* -maxdepth 1 -type d|while read APATH; do
				ALBUM=$(echo "$APATH"|cut -d'/' -f3)
				echo mv -v "$i/$ALBUM" "$PWD"/"$BAND"/"$ALBUM"
			done
			echo rm -rv "$UPLOADPATH"/"$BAND"
		#fi
	done
fi
